// pages/work.vue
<script setup lang="ts">
useSeoMeta({
  title: 'Work | Dennis Smuda',
  ogTitle: 'Work | Dennis Smuda',
  description: 'All of my past projects! Feel free to check out my work and reach out if you have any questions!',
  ogDescription: 'All of my past projects! Feel free to check out my work and reach out if you have any questions!',
})
</script>

<template>
  <SharedPageTitle title="work 🏁" subtitle="let's see some of my projects" />

  <WidgetWork />
</template>

<style scoped>
h1 {
  view-transition-name: header;
}
</style>

// src/routes/work/+page.svelte
<script>
	import Projects from '$lib/features/projects/index.svelte'
</script>

<svelte:head>
	<title>Work | Dennis Smuda</title>
	<meta
		name="description"
		content="All of my past projects! Feel free to check out my work and reach out if you have any questions!"
	/>
	<meta property="og:title" content="Work | Dennis Smuda" />
	<meta
		property="og:description"
		content="All of my past projects! Feel free to check out my work and reach out if you have any questions!"
	/>
</svelte:head>

<Projects />
