// src/lib/features/home/index.svelte
<script>
	import Hero from './hero.svelte'
	import HomeSidebar from './sidebar.svelte'

	import Project from '$lib/features/projects/project.svelte'
	import { topProjects } from '$lib/data/projects'
</script>

<!-- Hero -->
<Hero />

<!-- Project List + Sidebar -->
<section
	class="flex flex-col-reverse max-w-lg md:max-w-2xl md:grid p-8 gap-16 md:grid-cols-12 container mx-auto lg:max-w-4xl"
>
	<article class="ds-prose col-span-7 md:mt-20">
		<h2 class="rotated">latest work 🏁</h2>

		{#each topProjects as project}
			<Project
				url={project.url}
				headline={project.headline}
				subline={project.subline}
				description={project.description}
			/>
		{/each}
	</article>

	<aside class="ds-prose col-span-5 -mt-12">
		<h2 class="rotated">making things with 🛠</h2>

		<HomeSidebar />
	</aside>
</section>

// widgets/home/Home.vue
<template>
  <section
    class="flex flex-col max-w-lg md:max-w-2xl md:grid p-8 gap-16 md:grid-cols-12 container mx-auto lg:max-w-4xl"
  >
    <article class="ds-prose col-span-7 md:mt-8">
      <h2 data-testid="rotated-heading" class="rotated">
        latest work 🏁
      </h2>
      <FeatureProjectsLatestProjects />
    </article>

    <div class="ds-prose col-span-5 -mt-12 flex flex-col-reverse md:flex-col">
      <div>
        <h2 data-testid="rotated-heading" class="rotated pt-20 md:pt-0">
          making things with 🛠
        </h2>
        <FeatureTagsSidebar />
      </div>

      <!-- Latest Posts -->
      <div>
        <h2 data-testid="rotated-heading" class="rotated">
          latest posts ✏️
        </h2>
        <FeaturePostsLatestPosts />
      </div>
    </div>
  </section>
</template>
